// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpsoupsfckjcysthjxso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc291cHNmY2tqY3lzdGhqeHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNjA0ODEsImV4cCI6MjA1NDYzNjQ4MX0.-P0UtHqqELkBJ4_LhISVuCXFQTFEe0skPOJe84t1Dcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);